// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine_api.dart';

import 'dart:async';
import 'dart:convert';

import 'engine/events.dart';
import 'engine/models.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiEngineApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -855532043;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'offline_audio',
        ioDirectory: '../rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<PlatformInt64> crateApiEngineApiActiveDownloadCount();

  Future<void> crateApiEngineApiAddToPlaylist({
    required String playlistId,
    required String trackId,
  });

  Future<AppDirs> crateApiEngineApiAppDirs();

  Future<BinariesStatus> crateApiEngineApiBinariesStatus();

  Future<void> crateApiEngineApiCancelDownload({required String taskId});

  Future<void> crateApiEngineApiCheckYtdlp();

  Future<Playlist> crateApiEngineApiCreatePlaylist({required String name});

  Future<void> crateApiEngineApiDeletePlaylist({required String id});

  Future<Track?> crateApiEngineApiDeleteTrack({required String id});

  Future<void> crateApiEngineApiDownloadMobileBinaries();

  Stream<Event> crateApiEngineApiEventStream();

  Future<List<Track>> crateApiEngineApiGetLibrary({
    String? search,
    required SortOrder order,
  });

  Future<String?> crateApiEngineApiGetSetting({required String key});

  Future<Track?> crateApiEngineApiGetTrack({required String id});

  Future<YtdlpInfo> crateApiEngineApiGetYtdlpStatus();

  Future<void> crateApiEngineApiInitApp();

  Future<List<Playlist>> crateApiEngineApiListPlaylists();

  Future<List<Track>> crateApiEngineApiPlaylistTracks({
    required String playlistId,
  });

  Future<ProbeInfo> crateApiEngineApiProbeUrl({required String url});

  Future<void> crateApiEngineApiRecordPlay({required String id});

  Future<void> crateApiEngineApiRemoveFromPlaylist({
    required String playlistId,
    required String trackId,
  });

  Future<void> crateApiEngineApiRenamePlaylist({
    required String id,
    required String name,
  });

  Future<void> crateApiEngineApiReorderPlaylist({
    required String playlistId,
    required List<String> orderedTrackIds,
  });

  Future<void> crateApiEngineApiSetSetting({
    required String key,
    required String value,
  });

  Future<String> crateApiEngineApiStartDownload({
    required String url,
    required ContentKind kind,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PlatformInt64> crateApiEngineApiActiveDownloadCount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiActiveDownloadCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiActiveDownloadCountConstMeta =>
      const TaskConstMeta(debugName: "active_download_count", argNames: []);

  @override
  Future<void> crateApiEngineApiAddToPlaylist({
    required String playlistId,
    required String trackId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(playlistId, serializer);
          sse_encode_String(trackId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiAddToPlaylistConstMeta,
        argValues: [playlistId, trackId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiAddToPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "add_to_playlist",
        argNames: ["playlistId", "trackId"],
      );

  @override
  Future<AppDirs> crateApiEngineApiAppDirs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_dirs,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiAppDirsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiAppDirsConstMeta =>
      const TaskConstMeta(debugName: "app_dirs", argNames: []);

  @override
  Future<BinariesStatus> crateApiEngineApiBinariesStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_binaries_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiBinariesStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiBinariesStatusConstMeta =>
      const TaskConstMeta(debugName: "binaries_status", argNames: []);

  @override
  Future<void> crateApiEngineApiCancelDownload({required String taskId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiCancelDownloadConstMeta,
        argValues: [taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiCancelDownloadConstMeta =>
      const TaskConstMeta(debugName: "cancel_download", argNames: ["taskId"]);

  @override
  Future<void> crateApiEngineApiCheckYtdlp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiCheckYtdlpConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiCheckYtdlpConstMeta =>
      const TaskConstMeta(debugName: "check_ytdlp", argNames: []);

  @override
  Future<Playlist> crateApiEngineApiCreatePlaylist({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playlist,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiCreatePlaylistConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiCreatePlaylistConstMeta =>
      const TaskConstMeta(debugName: "create_playlist", argNames: ["name"]);

  @override
  Future<void> crateApiEngineApiDeletePlaylist({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiDeletePlaylistConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiDeletePlaylistConstMeta =>
      const TaskConstMeta(debugName: "delete_playlist", argNames: ["id"]);

  @override
  Future<Track?> crateApiEngineApiDeleteTrack({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_track,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiDeleteTrackConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiDeleteTrackConstMeta =>
      const TaskConstMeta(debugName: "delete_track", argNames: ["id"]);

  @override
  Future<void> crateApiEngineApiDownloadMobileBinaries() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiDownloadMobileBinariesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiDownloadMobileBinariesConstMeta =>
      const TaskConstMeta(debugName: "download_mobile_binaries", argNames: []);

  @override
  Stream<Event> crateApiEngineApiEventStream() {
    final sink = RustStreamSink<Event>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiEngineApiEventStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEngineApiEventStreamConstMeta =>
      const TaskConstMeta(debugName: "event_stream", argNames: ["sink"]);

  @override
  Future<List<Track>> crateApiEngineApiGetLibrary({
    String? search,
    required SortOrder order,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(search, serializer);
          sse_encode_sort_order(order, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiGetLibraryConstMeta,
        argValues: [search, order],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiGetLibraryConstMeta =>
      const TaskConstMeta(
        debugName: "get_library",
        argNames: ["search", "order"],
      );

  @override
  Future<String?> crateApiEngineApiGetSetting({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiGetSettingConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiGetSettingConstMeta =>
      const TaskConstMeta(debugName: "get_setting", argNames: ["key"]);

  @override
  Future<Track?> crateApiEngineApiGetTrack({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_track,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiGetTrackConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiGetTrackConstMeta =>
      const TaskConstMeta(debugName: "get_track", argNames: ["id"]);

  @override
  Future<YtdlpInfo> crateApiEngineApiGetYtdlpStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ytdlp_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiGetYtdlpStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiGetYtdlpStatusConstMeta =>
      const TaskConstMeta(debugName: "get_ytdlp_status", argNames: []);

  @override
  Future<void> crateApiEngineApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<Playlist>> crateApiEngineApiListPlaylists() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_playlist,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiListPlaylistsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiListPlaylistsConstMeta =>
      const TaskConstMeta(debugName: "list_playlists", argNames: []);

  @override
  Future<List<Track>> crateApiEngineApiPlaylistTracks({
    required String playlistId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(playlistId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiPlaylistTracksConstMeta,
        argValues: [playlistId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiPlaylistTracksConstMeta =>
      const TaskConstMeta(
        debugName: "playlist_tracks",
        argNames: ["playlistId"],
      );

  @override
  Future<ProbeInfo> crateApiEngineApiProbeUrl({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_probe_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiProbeUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiProbeUrlConstMeta =>
      const TaskConstMeta(debugName: "probe_url", argNames: ["url"]);

  @override
  Future<void> crateApiEngineApiRecordPlay({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiRecordPlayConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiRecordPlayConstMeta =>
      const TaskConstMeta(debugName: "record_play", argNames: ["id"]);

  @override
  Future<void> crateApiEngineApiRemoveFromPlaylist({
    required String playlistId,
    required String trackId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(playlistId, serializer);
          sse_encode_String(trackId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiRemoveFromPlaylistConstMeta,
        argValues: [playlistId, trackId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiRemoveFromPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "remove_from_playlist",
        argNames: ["playlistId", "trackId"],
      );

  @override
  Future<void> crateApiEngineApiRenamePlaylist({
    required String id,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiRenamePlaylistConstMeta,
        argValues: [id, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiRenamePlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "rename_playlist",
        argNames: ["id", "name"],
      );

  @override
  Future<void> crateApiEngineApiReorderPlaylist({
    required String playlistId,
    required List<String> orderedTrackIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(playlistId, serializer);
          sse_encode_list_String(orderedTrackIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiReorderPlaylistConstMeta,
        argValues: [playlistId, orderedTrackIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiReorderPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "reorder_playlist",
        argNames: ["playlistId", "orderedTrackIds"],
      );

  @override
  Future<void> crateApiEngineApiSetSetting({
    required String key,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiSetSettingConstMeta,
        argValues: [key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetSettingConstMeta =>
      const TaskConstMeta(debugName: "set_setting", argNames: ["key", "value"]);

  @override
  Future<String> crateApiEngineApiStartDownload({
    required String url,
    required ContentKind kind,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_content_kind(kind, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineApiStartDownloadConstMeta,
        argValues: [url, kind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiStartDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "start_download",
        argNames: ["url", "kind"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<Event> dco_decode_StreamSink_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppDirs dco_decode_app_dirs(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AppDirs(
      home: dco_decode_String(arr[0]),
      cache: dco_decode_String(arr[1]),
      thumbs: dco_decode_String(arr[2]),
      tmp: dco_decode_String(arr[3]),
    );
  }

  @protected
  BinariesStatus dco_decode_binaries_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BinariesStatus(
      ytDlpPresent: dco_decode_bool(arr[0]),
      ffmpegPresent: dco_decode_bool(arr[1]),
      binDir: dco_decode_String(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  Track dco_decode_box_autoadd_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_track(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ContentKind dco_decode_content_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ContentKind.values[raw as int];
  }

  @protected
  Event dco_decode_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Event_DownloadProgress(
          taskId: dco_decode_String(raw[1]),
          percent: dco_decode_f_32(raw[2]),
          downloadedBytes: dco_decode_u_64(raw[3]),
          totalBytes: dco_decode_opt_box_autoadd_u_64(raw[4]),
          speedBytesSec: dco_decode_opt_box_autoadd_u_64(raw[5]),
          etaSecs: dco_decode_opt_box_autoadd_u_64(raw[6]),
        );
      case 1:
        return Event_DownloadFinished(
          taskId: dco_decode_String(raw[1]),
          track: dco_decode_box_autoadd_track(raw[2]),
        );
      case 2:
        return Event_DownloadFailed(
          taskId: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 3:
        return Event_DownloadCancelled(taskId: dco_decode_String(raw[1]));
      case 4:
        return Event_DownloadSkippedDuplicate(
          taskId: dco_decode_String(raw[1]),
          track: dco_decode_box_autoadd_track(raw[2]),
        );
      case 5:
        return Event_YtdlpStatus(
          present: dco_decode_bool(raw[1]),
          version: dco_decode_opt_String(raw[2]),
          outdated: dco_decode_bool(raw[3]),
          lastChecked: dco_decode_opt_String(raw[4]),
          message: dco_decode_opt_String(raw[5]),
        );
      case 6:
        return Event_Notify(
          kind: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 7:
        return Event_LibraryChanged();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Playlist> dco_decode_list_playlist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_playlist).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Track> dco_decode_list_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  Track? dco_decode_opt_box_autoadd_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_track(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Playlist dco_decode_playlist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Playlist(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      createdDate: dco_decode_String(arr[2]),
      trackCount: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  ProbeInfo dco_decode_probe_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return ProbeInfo(
      id: dco_decode_String(arr[0]),
      sourceId: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      artist: dco_decode_opt_String(arr[3]),
      album: dco_decode_opt_String(arr[4]),
      genre: dco_decode_opt_String(arr[5]),
      durationSeconds: dco_decode_opt_box_autoadd_i_64(arr[6]),
      thumbnailUrl: dco_decode_opt_String(arr[7]),
      platform: dco_decode_opt_String(arr[8]),
      uploader: dco_decode_opt_String(arr[9]),
      webpageUrl: dco_decode_opt_String(arr[10]),
      estimatedSizeBytes: dco_decode_opt_box_autoadd_u_64(arr[11]),
      likelySpeech: dco_decode_bool(arr[12]),
    );
  }

  @protected
  SortOrder dco_decode_sort_order(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SortOrder.values[raw as int];
  }

  @protected
  Track dco_decode_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return Track(
      id: dco_decode_String(arr[0]),
      sourceId: dco_decode_String(arr[1]),
      networkUrl: dco_decode_String(arr[2]),
      title: dco_decode_String(arr[3]),
      artist: dco_decode_opt_String(arr[4]),
      album: dco_decode_opt_String(arr[5]),
      genre: dco_decode_opt_String(arr[6]),
      durationSeconds: dco_decode_opt_box_autoadd_i_64(arr[7]),
      filePath: dco_decode_String(arr[8]),
      thumbnailPath: dco_decode_opt_String(arr[9]),
      platform: dco_decode_opt_String(arr[10]),
      contentKind: dco_decode_String(arr[11]),
      bitrateKbps: dco_decode_opt_box_autoadd_i_64(arr[12]),
      downloadDate: dco_decode_String(arr[13]),
      playCount: dco_decode_i_64(arr[14]),
      lastPlayed: dco_decode_opt_String(arr[15]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  YtdlpInfo dco_decode_ytdlp_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return YtdlpInfo(
      present: dco_decode_bool(arr[0]),
      version: dco_decode_opt_String(arr[1]),
      outdated: dco_decode_bool(arr[2]),
      lastChecked: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<Event> sse_decode_StreamSink_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppDirs sse_decode_app_dirs(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_home = sse_decode_String(deserializer);
    var var_cache = sse_decode_String(deserializer);
    var var_thumbs = sse_decode_String(deserializer);
    var var_tmp = sse_decode_String(deserializer);
    return AppDirs(
      home: var_home,
      cache: var_cache,
      thumbs: var_thumbs,
      tmp: var_tmp,
    );
  }

  @protected
  BinariesStatus sse_decode_binaries_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ytDlpPresent = sse_decode_bool(deserializer);
    var var_ffmpegPresent = sse_decode_bool(deserializer);
    var var_binDir = sse_decode_String(deserializer);
    return BinariesStatus(
      ytDlpPresent: var_ytDlpPresent,
      ffmpegPresent: var_ffmpegPresent,
      binDir: var_binDir,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  Track sse_decode_box_autoadd_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_track(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ContentKind sse_decode_content_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ContentKind.values[inner];
  }

  @protected
  Event sse_decode_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_taskId = sse_decode_String(deserializer);
        var var_percent = sse_decode_f_32(deserializer);
        var var_downloadedBytes = sse_decode_u_64(deserializer);
        var var_totalBytes = sse_decode_opt_box_autoadd_u_64(deserializer);
        var var_speedBytesSec = sse_decode_opt_box_autoadd_u_64(deserializer);
        var var_etaSecs = sse_decode_opt_box_autoadd_u_64(deserializer);
        return Event_DownloadProgress(
          taskId: var_taskId,
          percent: var_percent,
          downloadedBytes: var_downloadedBytes,
          totalBytes: var_totalBytes,
          speedBytesSec: var_speedBytesSec,
          etaSecs: var_etaSecs,
        );
      case 1:
        var var_taskId = sse_decode_String(deserializer);
        var var_track = sse_decode_box_autoadd_track(deserializer);
        return Event_DownloadFinished(taskId: var_taskId, track: var_track);
      case 2:
        var var_taskId = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return Event_DownloadFailed(taskId: var_taskId, reason: var_reason);
      case 3:
        var var_taskId = sse_decode_String(deserializer);
        return Event_DownloadCancelled(taskId: var_taskId);
      case 4:
        var var_taskId = sse_decode_String(deserializer);
        var var_track = sse_decode_box_autoadd_track(deserializer);
        return Event_DownloadSkippedDuplicate(
          taskId: var_taskId,
          track: var_track,
        );
      case 5:
        var var_present = sse_decode_bool(deserializer);
        var var_version = sse_decode_opt_String(deserializer);
        var var_outdated = sse_decode_bool(deserializer);
        var var_lastChecked = sse_decode_opt_String(deserializer);
        var var_message = sse_decode_opt_String(deserializer);
        return Event_YtdlpStatus(
          present: var_present,
          version: var_version,
          outdated: var_outdated,
          lastChecked: var_lastChecked,
          message: var_message,
        );
      case 6:
        var var_kind = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return Event_Notify(kind: var_kind, message: var_message);
      case 7:
        return Event_LibraryChanged();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Playlist> sse_decode_list_playlist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Playlist>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_playlist(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Track> sse_decode_list_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Track>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Track? sse_decode_opt_box_autoadd_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_track(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Playlist sse_decode_playlist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_createdDate = sse_decode_String(deserializer);
    var var_trackCount = sse_decode_i_64(deserializer);
    return Playlist(
      id: var_id,
      name: var_name,
      createdDate: var_createdDate,
      trackCount: var_trackCount,
    );
  }

  @protected
  ProbeInfo sse_decode_probe_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sourceId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_genre = sse_decode_opt_String(deserializer);
    var var_durationSeconds = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_thumbnailUrl = sse_decode_opt_String(deserializer);
    var var_platform = sse_decode_opt_String(deserializer);
    var var_uploader = sse_decode_opt_String(deserializer);
    var var_webpageUrl = sse_decode_opt_String(deserializer);
    var var_estimatedSizeBytes = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_likelySpeech = sse_decode_bool(deserializer);
    return ProbeInfo(
      id: var_id,
      sourceId: var_sourceId,
      title: var_title,
      artist: var_artist,
      album: var_album,
      genre: var_genre,
      durationSeconds: var_durationSeconds,
      thumbnailUrl: var_thumbnailUrl,
      platform: var_platform,
      uploader: var_uploader,
      webpageUrl: var_webpageUrl,
      estimatedSizeBytes: var_estimatedSizeBytes,
      likelySpeech: var_likelySpeech,
    );
  }

  @protected
  SortOrder sse_decode_sort_order(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SortOrder.values[inner];
  }

  @protected
  Track sse_decode_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sourceId = sse_decode_String(deserializer);
    var var_networkUrl = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_genre = sse_decode_opt_String(deserializer);
    var var_durationSeconds = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    var var_thumbnailPath = sse_decode_opt_String(deserializer);
    var var_platform = sse_decode_opt_String(deserializer);
    var var_contentKind = sse_decode_String(deserializer);
    var var_bitrateKbps = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_downloadDate = sse_decode_String(deserializer);
    var var_playCount = sse_decode_i_64(deserializer);
    var var_lastPlayed = sse_decode_opt_String(deserializer);
    return Track(
      id: var_id,
      sourceId: var_sourceId,
      networkUrl: var_networkUrl,
      title: var_title,
      artist: var_artist,
      album: var_album,
      genre: var_genre,
      durationSeconds: var_durationSeconds,
      filePath: var_filePath,
      thumbnailPath: var_thumbnailPath,
      platform: var_platform,
      contentKind: var_contentKind,
      bitrateKbps: var_bitrateKbps,
      downloadDate: var_downloadDate,
      playCount: var_playCount,
      lastPlayed: var_lastPlayed,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  YtdlpInfo sse_decode_ytdlp_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_present = sse_decode_bool(deserializer);
    var var_version = sse_decode_opt_String(deserializer);
    var var_outdated = sse_decode_bool(deserializer);
    var var_lastChecked = sse_decode_opt_String(deserializer);
    return YtdlpInfo(
      present: var_present,
      version: var_version,
      outdated: var_outdated,
      lastChecked: var_lastChecked,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_event_Sse(
    RustStreamSink<Event> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_dirs(AppDirs self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.home, serializer);
    sse_encode_String(self.cache, serializer);
    sse_encode_String(self.thumbs, serializer);
    sse_encode_String(self.tmp, serializer);
  }

  @protected
  void sse_encode_binaries_status(
    BinariesStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ytDlpPresent, serializer);
    sse_encode_bool(self.ffmpegPresent, serializer);
    sse_encode_String(self.binDir, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_track(Track self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_track(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_content_kind(ContentKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_event(Event self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Event_DownloadProgress(
        taskId: final taskId,
        percent: final percent,
        downloadedBytes: final downloadedBytes,
        totalBytes: final totalBytes,
        speedBytesSec: final speedBytesSec,
        etaSecs: final etaSecs,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_f_32(percent, serializer);
        sse_encode_u_64(downloadedBytes, serializer);
        sse_encode_opt_box_autoadd_u_64(totalBytes, serializer);
        sse_encode_opt_box_autoadd_u_64(speedBytesSec, serializer);
        sse_encode_opt_box_autoadd_u_64(etaSecs, serializer);
      case Event_DownloadFinished(taskId: final taskId, track: final track):
        sse_encode_i_32(1, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_box_autoadd_track(track, serializer);
      case Event_DownloadFailed(taskId: final taskId, reason: final reason):
        sse_encode_i_32(2, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_String(reason, serializer);
      case Event_DownloadCancelled(taskId: final taskId):
        sse_encode_i_32(3, serializer);
        sse_encode_String(taskId, serializer);
      case Event_DownloadSkippedDuplicate(
        taskId: final taskId,
        track: final track,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_box_autoadd_track(track, serializer);
      case Event_YtdlpStatus(
        present: final present,
        version: final version,
        outdated: final outdated,
        lastChecked: final lastChecked,
        message: final message,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_bool(present, serializer);
        sse_encode_opt_String(version, serializer);
        sse_encode_bool(outdated, serializer);
        sse_encode_opt_String(lastChecked, serializer);
        sse_encode_opt_String(message, serializer);
      case Event_Notify(kind: final kind, message: final message):
        sse_encode_i_32(6, serializer);
        sse_encode_String(kind, serializer);
        sse_encode_String(message, serializer);
      case Event_LibraryChanged():
        sse_encode_i_32(7, serializer);
    }
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_playlist(List<Playlist> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_playlist(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_track(List<Track> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_track(Track? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_track(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_playlist(Playlist self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.createdDate, serializer);
    sse_encode_i_64(self.trackCount, serializer);
  }

  @protected
  void sse_encode_probe_info(ProbeInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.sourceId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_String(self.genre, serializer);
    sse_encode_opt_box_autoadd_i_64(self.durationSeconds, serializer);
    sse_encode_opt_String(self.thumbnailUrl, serializer);
    sse_encode_opt_String(self.platform, serializer);
    sse_encode_opt_String(self.uploader, serializer);
    sse_encode_opt_String(self.webpageUrl, serializer);
    sse_encode_opt_box_autoadd_u_64(self.estimatedSizeBytes, serializer);
    sse_encode_bool(self.likelySpeech, serializer);
  }

  @protected
  void sse_encode_sort_order(SortOrder self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_track(Track self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.sourceId, serializer);
    sse_encode_String(self.networkUrl, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_String(self.genre, serializer);
    sse_encode_opt_box_autoadd_i_64(self.durationSeconds, serializer);
    sse_encode_String(self.filePath, serializer);
    sse_encode_opt_String(self.thumbnailPath, serializer);
    sse_encode_opt_String(self.platform, serializer);
    sse_encode_String(self.contentKind, serializer);
    sse_encode_opt_box_autoadd_i_64(self.bitrateKbps, serializer);
    sse_encode_String(self.downloadDate, serializer);
    sse_encode_i_64(self.playCount, serializer);
    sse_encode_opt_String(self.lastPlayed, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_ytdlp_info(YtdlpInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.present, serializer);
    sse_encode_opt_String(self.version, serializer);
    sse_encode_bool(self.outdated, serializer);
    sse_encode_opt_String(self.lastChecked, serializer);
  }
}
