// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

@freezed
sealed class Event with _$Event {
  const Event._();

  /// Progress of an active download task.
  const factory Event.downloadProgress({
    required String taskId,
    required double percent,
    required BigInt downloadedBytes,
    BigInt? totalBytes,
    BigInt? speedBytesSec,
    BigInt? etaSecs,
  }) = Event_DownloadProgress;

  /// A download finished and the track was persisted.
  const factory Event.downloadFinished({
    required String taskId,
    required Track track,
  }) = Event_DownloadFinished;

  /// A download failed (reason is human readable, in the app language).
  const factory Event.downloadFailed({
    required String taskId,
    required String reason,
  }) = Event_DownloadFailed;

  /// The user cancelled the task.
  const factory Event.downloadCancelled({required String taskId}) =
      Event_DownloadCancelled;

  /// The source was already present in the library; nothing was downloaded.
  const factory Event.downloadSkippedDuplicate({
    required String taskId,
    required Track track,
  }) = Event_DownloadSkippedDuplicate;

  /// Result of a background yt-dlp version check / update.
  const factory Event.ytdlpStatus({
    required bool present,
    String? version,
    required bool outdated,
    String? lastChecked,
    String? message,
  }) = Event_YtdlpStatus;

  /// Generic UI notification (e.g. snackbar).
  const factory Event.notify({required String kind, required String message}) =
      Event_Notify;

  /// Something that affects the library changed.
  const factory Event.libraryChanged() = Event_LibraryChanged;
}
