// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum ContentKind { music, speech, video }

class Playlist {
  final String id;
  final String name;
  final String createdDate;
  final PlatformInt64 trackCount;

  const Playlist({
    required this.id,
    required this.name,
    required this.createdDate,
    required this.trackCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ createdDate.hashCode ^ trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Playlist &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdDate == other.createdDate &&
          trackCount == other.trackCount;
}

class ProbeInfo {
  final String id;
  final String sourceId;
  final String title;
  final String? artist;
  final String? album;
  final String? genre;
  final PlatformInt64? durationSeconds;
  final String? thumbnailUrl;
  final String? platform;
  final String? uploader;
  final String? webpageUrl;
  final BigInt? estimatedSizeBytes;

  /// True when the content looks more like speech/podcast than music.
  final bool likelySpeech;

  const ProbeInfo({
    required this.id,
    required this.sourceId,
    required this.title,
    this.artist,
    this.album,
    this.genre,
    this.durationSeconds,
    this.thumbnailUrl,
    this.platform,
    this.uploader,
    this.webpageUrl,
    this.estimatedSizeBytes,
    required this.likelySpeech,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sourceId.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      genre.hashCode ^
      durationSeconds.hashCode ^
      thumbnailUrl.hashCode ^
      platform.hashCode ^
      uploader.hashCode ^
      webpageUrl.hashCode ^
      estimatedSizeBytes.hashCode ^
      likelySpeech.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProbeInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceId == other.sourceId &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          genre == other.genre &&
          durationSeconds == other.durationSeconds &&
          thumbnailUrl == other.thumbnailUrl &&
          platform == other.platform &&
          uploader == other.uploader &&
          webpageUrl == other.webpageUrl &&
          estimatedSizeBytes == other.estimatedSizeBytes &&
          likelySpeech == other.likelySpeech;
}

enum SortOrder {
  /// Title A-Z.
  titleAsc,

  /// Title Z-A.
  titleDesc,

  /// Newest download first (default).
  dateDesc,

  /// Oldest download first.
  dateAsc,
}

class Track {
  final String id;

  /// Canonical `{extractor}:{video_id}` used for de-duplication.
  final String sourceId;
  final String networkUrl;
  final String title;
  final String? artist;
  final String? album;
  final String? genre;
  final PlatformInt64? durationSeconds;

  /// Absolute path to the cached `.opus` file (hashed name).
  final String filePath;
  final String? thumbnailPath;
  final String? platform;

  /// `"music"` or `"speech"`.
  final String contentKind;
  final PlatformInt64? bitrateKbps;

  /// RFC3339 UTC.
  final String downloadDate;
  final PlatformInt64 playCount;
  final String? lastPlayed;

  const Track({
    required this.id,
    required this.sourceId,
    required this.networkUrl,
    required this.title,
    this.artist,
    this.album,
    this.genre,
    this.durationSeconds,
    required this.filePath,
    this.thumbnailPath,
    this.platform,
    required this.contentKind,
    this.bitrateKbps,
    required this.downloadDate,
    required this.playCount,
    this.lastPlayed,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sourceId.hashCode ^
      networkUrl.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      genre.hashCode ^
      durationSeconds.hashCode ^
      filePath.hashCode ^
      thumbnailPath.hashCode ^
      platform.hashCode ^
      contentKind.hashCode ^
      bitrateKbps.hashCode ^
      downloadDate.hashCode ^
      playCount.hashCode ^
      lastPlayed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceId == other.sourceId &&
          networkUrl == other.networkUrl &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          genre == other.genre &&
          durationSeconds == other.durationSeconds &&
          filePath == other.filePath &&
          thumbnailPath == other.thumbnailPath &&
          platform == other.platform &&
          contentKind == other.contentKind &&
          bitrateKbps == other.bitrateKbps &&
          downloadDate == other.downloadDate &&
          playCount == other.playCount &&
          lastPlayed == other.lastPlayed;
}
