// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine/events.dart';
import '../engine/models.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine_ref`

/// Query metadata for a URL without downloading anything.
Future<ProbeInfo> probeUrl({required String url}) =>
    RustLib.instance.api.crateApiEngineApiProbeUrl(url: url);

/// Start a download+convert task. Returns a task id; progress and result are
/// delivered on the event stream.
Future<String> startDownload({
  required String url,
  required ContentKind kind,
}) => RustLib.instance.api.crateApiEngineApiStartDownload(url: url, kind: kind);

/// Cancel a running download task.
Future<void> cancelDownload({required String taskId}) =>
    RustLib.instance.api.crateApiEngineApiCancelDownload(taskId: taskId);

/// Number of currently active downloads.
Future<PlatformInt64> activeDownloadCount() =>
    RustLib.instance.api.crateApiEngineApiActiveDownloadCount();

Future<List<Track>> getLibrary({String? search, required SortOrder order}) =>
    RustLib.instance.api.crateApiEngineApiGetLibrary(
      search: search,
      order: order,
    );

Future<Track?> getTrack({required String id}) =>
    RustLib.instance.api.crateApiEngineApiGetTrack(id: id);

/// Delete a track from the library and remove its cached files.
Future<Track?> deleteTrack({required String id}) =>
    RustLib.instance.api.crateApiEngineApiDeleteTrack(id: id);

/// Record a playback: bumps play_count and stamps last_played.
Future<void> recordPlay({required String id}) =>
    RustLib.instance.api.crateApiEngineApiRecordPlay(id: id);

Future<Playlist> createPlaylist({required String name}) =>
    RustLib.instance.api.crateApiEngineApiCreatePlaylist(name: name);

Future<void> renamePlaylist({required String id, required String name}) =>
    RustLib.instance.api.crateApiEngineApiRenamePlaylist(id: id, name: name);

Future<void> deletePlaylist({required String id}) =>
    RustLib.instance.api.crateApiEngineApiDeletePlaylist(id: id);

Future<List<Playlist>> listPlaylists() =>
    RustLib.instance.api.crateApiEngineApiListPlaylists();

Future<void> addToPlaylist({
  required String playlistId,
  required String trackId,
}) => RustLib.instance.api.crateApiEngineApiAddToPlaylist(
  playlistId: playlistId,
  trackId: trackId,
);

Future<void> removeFromPlaylist({
  required String playlistId,
  required String trackId,
}) => RustLib.instance.api.crateApiEngineApiRemoveFromPlaylist(
  playlistId: playlistId,
  trackId: trackId,
);

Future<void> reorderPlaylist({
  required String playlistId,
  required List<String> orderedTrackIds,
}) => RustLib.instance.api.crateApiEngineApiReorderPlaylist(
  playlistId: playlistId,
  orderedTrackIds: orderedTrackIds,
);

Future<List<Track>> playlistTracks({required String playlistId}) => RustLib
    .instance
    .api
    .crateApiEngineApiPlaylistTracks(playlistId: playlistId);

Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiEngineApiGetSetting(key: key);

Future<void> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiEngineApiSetSetting(key: key, value: value);

Future<AppDirs> appDirs() => RustLib.instance.api.crateApiEngineApiAppDirs();

/// Snapshot of the last yt-dlp check (from persisted settings).
Future<YtdlpInfo> getYtdlpStatus() =>
    RustLib.instance.api.crateApiEngineApiGetYtdlpStatus();

/// Run the yt-dlp check/update in the background. Results arrive as a
/// `YtdlpStatus` event.
Future<void> checkYtdlp() => RustLib.instance.api.crateApiEngineApiCheckYtdlp();

/// Subscribe to engine events. The returned stream must be listened to as a
/// native Dart stream (`RustStreamSink`).
Stream<Event> eventStream() =>
    RustLib.instance.api.crateApiEngineApiEventStream();

class AppDirs {
  final String home;
  final String cache;
  final String thumbs;
  final String tmp;

  const AppDirs({
    required this.home,
    required this.cache,
    required this.thumbs,
    required this.tmp,
  });

  @override
  int get hashCode =>
      home.hashCode ^ cache.hashCode ^ thumbs.hashCode ^ tmp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppDirs &&
          runtimeType == other.runtimeType &&
          home == other.home &&
          cache == other.cache &&
          thumbs == other.thumbs &&
          tmp == other.tmp;
}

class YtdlpInfo {
  final bool present;
  final String? version;
  final bool outdated;
  final String? lastChecked;

  const YtdlpInfo({
    required this.present,
    this.version,
    required this.outdated,
    this.lastChecked,
  });

  @override
  int get hashCode =>
      present.hashCode ^
      version.hashCode ^
      outdated.hashCode ^
      lastChecked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YtdlpInfo &&
          runtimeType == other.runtimeType &&
          present == other.present &&
          version == other.version &&
          outdated == other.outdated &&
          lastChecked == other.lastChecked;
}
