// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine/events.dart';
import '../engine/models.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dir_size`, `download_desktop_ffmpeg`, `engine_ref`, `init_logging`, `provision_engine_binaries`

Future<void> initApp() => RustLib.instance.api.crateApiEngineApiInitApp();

/// Query metadata for a URL without downloading anything.
Future<ProbeInfo> probeUrl({required String url}) =>
    RustLib.instance.api.crateApiEngineApiProbeUrl(url: url);

/// Resolve a direct stream URL for previewing a result without downloading.
/// Fallback path when the Dart library cannot fetch the manifest: yt-dlp
/// handles restricted videos and newer ciphers that break it. `video` picks
/// the progressive file selection, otherwise best audio.
Future<String> previewStreamUrl({required String url, required bool video}) =>
    RustLib.instance.api.crateApiEngineApiPreviewStreamUrl(
      url: url,
      video: video,
    );

/// Start a download+convert task. Returns a task id; progress and result are
/// delivered on the event stream.
Future<String> startDownload({
  required String url,
  required ContentKind kind,
}) => RustLib.instance.api.crateApiEngineApiStartDownload(url: url, kind: kind);

/// Persist a media file downloaded by a platform-native backend.
///
/// Android uses youtubedl-android/ffmpeg-kit because Android 10+ blocks
/// executing the CLI runtime from the writable app directory. Dart owns the
/// native task lifecycle and sends the finished Track back here for storage.
Future<void> persistExternalTrack({required Track track}) =>
    RustLib.instance.api.crateApiEngineApiPersistExternalTrack(track: track);

/// Cancel a running download task.
Future<void> cancelDownload({required String taskId}) =>
    RustLib.instance.api.crateApiEngineApiCancelDownload(taskId: taskId);

/// Number of currently active downloads.
Future<PlatformInt64> activeDownloadCount() =>
    RustLib.instance.api.crateApiEngineApiActiveDownloadCount();

Future<List<Track>> getLibrary({String? search, required SortOrder order}) =>
    RustLib.instance.api.crateApiEngineApiGetLibrary(
      search: search,
      order: order,
    );

Future<Track?> getTrack({required String id}) =>
    RustLib.instance.api.crateApiEngineApiGetTrack(id: id);

/// Delete a track from the library and remove its cached files.
Future<Track?> deleteTrack({required String id}) =>
    RustLib.instance.api.crateApiEngineApiDeleteTrack(id: id);

/// Record a playback: bumps play_count and stamps last_played.
Future<void> recordPlay({required String id}) =>
    RustLib.instance.api.crateApiEngineApiRecordPlay(id: id);

/// Record a completed listen (playhead reached the end of the track):
/// bumps completed_count, accumulates listened seconds and refreshes
/// last_played. Feeds the expert shuffle.
Future<void> recordPlayCompleted({
  required String id,
  required PlatformInt64 listenedSeconds,
}) => RustLib.instance.api.crateApiEngineApiRecordPlayCompleted(
  id: id,
  listenedSeconds: listenedSeconds,
);

Future<Playlist> createPlaylist({required String name}) =>
    RustLib.instance.api.crateApiEngineApiCreatePlaylist(name: name);

Future<void> renamePlaylist({required String id, required String name}) =>
    RustLib.instance.api.crateApiEngineApiRenamePlaylist(id: id, name: name);

Future<void> deletePlaylist({required String id}) =>
    RustLib.instance.api.crateApiEngineApiDeletePlaylist(id: id);

Future<List<Playlist>> listPlaylists() =>
    RustLib.instance.api.crateApiEngineApiListPlaylists();

Future<void> addToPlaylist({
  required String playlistId,
  required String trackId,
}) => RustLib.instance.api.crateApiEngineApiAddToPlaylist(
  playlistId: playlistId,
  trackId: trackId,
);

Future<void> removeFromPlaylist({
  required String playlistId,
  required String trackId,
}) => RustLib.instance.api.crateApiEngineApiRemoveFromPlaylist(
  playlistId: playlistId,
  trackId: trackId,
);

Future<void> reorderPlaylist({
  required String playlistId,
  required List<String> orderedTrackIds,
}) => RustLib.instance.api.crateApiEngineApiReorderPlaylist(
  playlistId: playlistId,
  orderedTrackIds: orderedTrackIds,
);

Future<List<Track>> playlistTracks({required String playlistId}) => RustLib
    .instance
    .api
    .crateApiEngineApiPlaylistTracks(playlistId: playlistId);

Future<void> recordSearch({required String query, required String source}) =>
    RustLib.instance.api.crateApiEngineApiRecordSearch(
      query: query,
      source: source,
    );

Future<List<SearchHistoryEntry>> recentSearches({
  required String source,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiEngineApiRecentSearches(
  source: source,
  limit: limit,
);

Future<void> deleteSearch({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiEngineApiDeleteSearch(id: id);

Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiEngineApiGetSetting(key: key);

Future<void> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiEngineApiSetSetting(key: key, value: value);

Future<AppDirs> appDirs() => RustLib.instance.api.crateApiEngineApiAppDirs();

Future<StorageUsage> storageUsage() =>
    RustLib.instance.api.crateApiEngineApiStorageUsage();

/// Snapshot of the last yt-dlp check (from persisted settings).
Future<YtdlpInfo> getYtdlpStatus() =>
    RustLib.instance.api.crateApiEngineApiGetYtdlpStatus();

/// Run the yt-dlp check/update in the background. Results arrive as a
/// `YtdlpStatus` event.
Future<void> checkYtdlp() => RustLib.instance.api.crateApiEngineApiCheckYtdlp();

/// Fija el directorio base de datos del motor (db, caché, tmp, binarios).
/// En Android/iOS Dart pasa el directorio privado de la app antes de
/// cualquier otra llamada; en escritorio no se usa (vale `dirs::config_dir`).
Future<void> setAppDir({required String path}) =>
    RustLib.instance.api.crateApiEngineApiSetAppDir(path: path);

/// Presence of the runtime binaries used by the engine. Found in the app
/// `bin_dir` (runtime download), next to the executable (bundled, e.g. the
/// Windows .zip) or in PATH.
Future<BinariesStatus> binariesStatus() =>
    RustLib.instance.api.crateApiEngineApiBinariesStatus();

/// Garantiza yt-dlp + ffmpeg sin pedirle nada al usuario. Si ya están
/// (integrados en el release, en PATH o descargados antes) es un chequeo
/// barato; si falta alguno se descarga en silencio con las mismas fuentes
/// pineadas del release. Las descargas concurrentes se serializan con un
/// candado global para no bajar dos veces lo mismo. En caso de fallo
/// (p. ej. sin conexión) devuelve un error neutro: el arranque y los
/// reintentos lo volverán a intentar solos.
Future<void> ensureEngineBinaries() =>
    RustLib.instance.api.crateApiEngineApiEnsureEngineBinaries();

/// Compatibilidad: antes lo llamaba un botón de Ajustes (ya eliminado; el
/// motor se auto-abastece). Se mantiene expuesto por si hace falta
/// re-provisionar desde diagnósticos.
Future<void> downloadMobileBinaries() =>
    RustLib.instance.api.crateApiEngineApiDownloadMobileBinaries();

/// Subscribe to engine events. The returned stream must be listened to as a
/// native Dart stream (`RustStreamSink`).
Stream<Event> eventStream() =>
    RustLib.instance.api.crateApiEngineApiEventStream();

class AppDirs {
  final String home;
  final String cache;
  final String thumbs;
  final String tmp;

  const AppDirs({
    required this.home,
    required this.cache,
    required this.thumbs,
    required this.tmp,
  });

  @override
  int get hashCode =>
      home.hashCode ^ cache.hashCode ^ thumbs.hashCode ^ tmp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppDirs &&
          runtimeType == other.runtimeType &&
          home == other.home &&
          cache == other.cache &&
          thumbs == other.thumbs &&
          tmp == other.tmp;
}

class BinariesStatus {
  final bool ytDlpPresent;
  final bool ffmpegPresent;
  final String binDir;

  const BinariesStatus({
    required this.ytDlpPresent,
    required this.ffmpegPresent,
    required this.binDir,
  });

  @override
  int get hashCode =>
      ytDlpPresent.hashCode ^ ffmpegPresent.hashCode ^ binDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BinariesStatus &&
          runtimeType == other.runtimeType &&
          ytDlpPresent == other.ytDlpPresent &&
          ffmpegPresent == other.ffmpegPresent &&
          binDir == other.binDir;
}

/// Resumen de uso para Ajustes: nº de canciones en la biblioteca y bytes
/// totales en disco (audios + miniaturas + temporales). La UI no expone
/// rutas: solo esta cifra amigable.
class StorageUsage {
  final PlatformInt64 trackCount;
  final BigInt totalBytes;

  const StorageUsage({required this.trackCount, required this.totalBytes});

  @override
  int get hashCode => trackCount.hashCode ^ totalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageUsage &&
          runtimeType == other.runtimeType &&
          trackCount == other.trackCount &&
          totalBytes == other.totalBytes;
}

class YtdlpInfo {
  final bool present;
  final String? version;
  final bool outdated;
  final String? lastChecked;

  const YtdlpInfo({
    required this.present,
    this.version,
    required this.outdated,
    this.lastChecked,
  });

  @override
  int get hashCode =>
      present.hashCode ^
      version.hashCode ^
      outdated.hashCode ^
      lastChecked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YtdlpInfo &&
          runtimeType == other.runtimeType &&
          present == other.present &&
          version == other.version &&
          outdated == other.outdated &&
          lastChecked == other.lastChecked;
}
